language: cpp
compiler: gcc
install:
 - sudo apt-get install libqt4-dev qt4-qmake
 - sudo easy_install https://github.com/eddyxu/cpp-coveralls/archive/master.zip
script: qmake; make
after_success:
 - cd build/
 - cp ItchyPlusPlus obj/
 - cp -r ../src obj/
 - cd obj/
 - timeout 30s xvfb-run ./ItchyPlusPlus
 - gcov ./*
 - coveralls --exclude lib --exclude tests
# Change this to your needs

